### ISSUE TITLE
Imported forge server does not start

### ISSUE THREAD

**Issue by RiccardoBarbieri** [dwhitacre/WindowsGSM.ForgeMC#11]
When importing a already existing forge server and trying to start it, the server crashes instantly with this error:

`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more`

I'm no expert, maybe I'm doing something wrong, does anyone have the same problem?

**Comment by dwhitacre** [comment]
@RiccardoBarbieri hmmm is there anymore information you can provide? logs from both the minecraft server and from WGSM would be a good start. also if you could let me know what your forge jar and forge installer files in the imported directory look like (their names that is). also if you could indicate what modpack and version you are trying to import or if this is a vanilla forge server or a custom modpack etc.  

this plugin (as well as some of the other minecraft plugins for WGSM) have a couple big issues around version management amongst other things. ive tried to capture some of the issues in the other open issues in this repo if you'd like to take a look.

**Comment by dwhitacre** [comment]
fwiw, I am managing a Better Minecraft Server [Forge] v15 via this plugin since about when I launched v1 of this plugin. (~2 mos ago). this is what I did.

- downloaded server pack for the above mod pack
- ran the forge installer manually once (wgsm was crashing sometimes due to this taking a long time and using a lot of memory/cpu)
- then imported the directory in wgsm
- turned restart cronjob on, auto start on, backup on start on, and **auto update and auto restart leave off** (I leave **auto update disabled** as the version of the modpack is highly dependent on the forge version and letting forge auto upgrade would likely cause issues. I leave **auto restart disabled** as this was just causing startup issues with the restart cronjob)
- make sure to also up the memory given to forge in the details section (ie `-Xmx8G -Xms6G` or whatever is appropriate for your server/modpack)
- then started the server from there

I have noticed that backup on start doesnt actually get triggered on auto restart.... really annoying and sort of kills the whole point of wgsm for me here... but I have just been manually stopping and starting the server every couple of days to manually take a backup.
